server:
  port: 8080


spring:
  application.name: "tecpal"
  datasource:
    hikari: # https://github.com/brettwooldridge/HikariCP (uses milliseconds for all time values)
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    jpa.hibernate.ddl-auto: update
    h2:
      console:
        enabled: true
        path: /h2-console

logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html